### ISSUE TITLE
Not getting link of phishing page

### ISSUE THREAD

**Issue by Mr-vabs** [AbirHasan2005/ShellPhish#18]
Hello , I don't know what's causing this error but I'm not getting phishing link to share with victim.

**Comment by AbirHasan2005** [comment]
Use it in [Termux](https://termux.com) in Android. Must turn ON WiFi Hotspot & Mobile Data. Else it will not work.

**Comment by Mr-vabs** [comment]
Option 1 localhost is working fine.
Option 2 Ngrok now getting the link to send victim but it's returning null instead of login data
Option 3 not working tried with hotspot and turning on hotspot is working for 2nd option Ngrok not for this this option.
Option 4 is not working and showing "public key access denied".
