### ISSUE TITLE
Ngrok and serveo not working

### ISSUE THREAD

**Issue by aizaz321** [AbirHasan2005/ShellPhish#22]
Both ngrok and serveo not working and not showing any link

**Comment by AbirHasan2005** [comment]
Answered in #6 - https://github.com/AbirHasan2005/ShellPhish/issues/6#issuecomment-823644607

**Comment by aizaz321** [comment]
Hi.. the answer you mentioned is not working.. 

I installed in vm kali linux in windows.. execute your tool but there is no link showing ngrok and serveo..



You can also check by latest download...

**Comment by Drknoche** [comment]
> Answered in #6 - [#6 (comment)](https://github.com/AbirHasan2005/ShellPhish/issues/6#issuecomment-823644607)

Theres is no link asshole ngrok is not working whit phishing tools
