### ISSUE TITLE
Why not coming ngrok link?

### ISSUE THREAD

**Issue by ryhankabir562** [AbirHasan2005/ShellPhish#29]

**Comment by AbirHasan2005** [comment]
Turn ON WiFi Hotspot and Mobile Data connection together. It will work.

**Comment by ryhankabir562** [comment]
I want to use it in Kali Linux

> Turn ON WiFi Hotspot and Mobile Data connection together. It will work.

I want to use it in Kali Linux. But the "ngrok" link is not coming to Kali Linux. What can I do now? Do you have any suggestions or solutions for this?

**Comment by AbirHasan2005** [comment]
Not workable for Linux.

**Comment by ryhankabir562** [comment]
> Not workable for Linux.

That's true. But I came up with a new method. It's working on Linux. And thanks.
