### ISSUE TITLE
Where is link? Serveo.

### ISSUE THREAD

**Issue by toxasu** [AbirHasan2005/ShellPhish#6]
Where is link? Serveo.
![Screenshot_2020-12-21_18_48_49](https://user-images.githubusercontent.com/57259039/102801131-7a9e3280-43bd-11eb-86e0-1cb271f15866.png)

**Comment by AbirHasan2005** [comment]
> Where is link? Serveo.
> ![Screenshot_2020-12-21_18_48_49](https://user-images.githubusercontent.com/57259039/102801131-7a9e3280-43bd-11eb-86e0-1cb271f15866.png)

Using Kali Linux?

**Comment by abhi425-code** [comment]
Bro I got the same issue plzz help me I can't get the link it's blank

**Comment by AbirHasan2005** [comment]
> Bro I got the same issue plzz help me I can't get the link it's blank

This is only Modified for Termux. You have to Turn on WiFi Hotspot & Mobile Data together to make this work properly.

For more help ask in [Support Group](https://t.me/linux_repo)

**Comment by aizaz321** [comment]
It still not working..

**Comment by aizaz321** [comment]
I am using in window vm kali linux.. its not showing links and you closed my issue...

**Comment by AbirHasan2005** [comment]
> I am using in window vm kali linux.. its not showing links and you closed my issue...

lol, I already mentioned that it only works for Termux.

**Comment by ryhankabir562** [comment]
> > I am using in window vm kali linux.. its not showing links and you closed my issue...
> 
> lol, I already mentioned that it only works for Termux.

So why did you mention "SL"?
